baseURL = "http://louissay.com"
languageCode = "zh-CN"
title = "陆益思的博客"
theme = "maupassant"


[author]
  name = "Louis"

[params]
  author = "louis"
  subtitle = "学习,成长,投资."
  keywords = "陆益思的博客,博客,微服务,云计算,项目管理,软件架构,区块链,比特币,BTC,公众号,小程序"
  description = "专注于金融IT，包括但不限于开发、项目管理、软件架构、投资等"
  ## 这里我存放在了主题的static文件夹里，根目录的似乎也可以
  # customCSS = ['douban.css', 'other.css']
  # if ['custom.css'], load '/static/css/custom.css' file
  # customJS = ['douban.js']
  # if ['custom.js'], load '/static/js/custom.js' file 
  ## 是否禁止URL Path转小写
  disablePathToLower = true
  toc = true
  googleAnalytics = "UA-153269519-1"
  googleAd = ""
  ## 自定义文章摘要
  summaryLength = 140
  ## 自动检测是否包含中文/日文/韩文，该参数会影响摘要和字数统计功能，建议设置为true
  hasCJKLanguage = true
  ## 创建robots.txt，建议设置为true
  enableRobotsTXT = true
  ## algolia搜索
  algolia = "QEE4PPZIKV"

[params.busuanzi] # 是否使用不蒜子统计站点访问量
  enable = true
  siteUV = true
  sitePV = true
  pagePV = true

[menu]
  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 3

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[[params.links]]
  title = "陆益思的博客"
  name = "陆益思的博客"
  url = "http://louissay.com"
[[params.links]]
  title = "google搜索"
  name = "google搜索"
  url = "http://google.com"

[[params.ads]]
  title = "【高价格高返佣】企业级云服务器 1折特惠"
  url = "https://promotion.aliyun.com/ntms/act/enterprise-discount.html?userCode=wjowsdm5"
  img = "https://img.alicdn.com/tfs/TB1Gc3zmAL0gK0jSZFxXXXWHVXa-259-194.jpg"
[[params.ads]]
  title = "【大使渠道专属价】11月特惠 限时2折"
  url = "https://www.aliyun.com/acts/limit-buy?userCode=wjowsdm5"
  img = "https://img.alicdn.com/tfs/TB1hblJl7Y2gK0jSZFgXXc5OFXa-750-400.jpg"
[[params.ads]]
  title = "【全民云计算 老牌活动】云主机3年付低至3折"
  url = "https://promotion.aliyun.com/ntms/act/qwbk.html?userCode=wjowsdm5"
  img = "https://img.alicdn.com/tfs/TB1KmFynxz1gK0jSZSgXXavwpXa-200-126.jpg"
  



## 分类系统
[taxonomies]
  tag = "tags"
  category = "categories"

## 版权申明
[params.cc]
  name = "知识共享署名-非商业性使用-禁止演绎 4.0 国际许可协议"
  link = "https://creativecommons.org/licenses/by-nc-nd/4.0/"

## utteranc评论
[params.utteranc]
    enable = true
    repo = "louissay/blog-comment"    # 存储评论的Repo，格式为 owner/repo
    issueTerm = "title"  #表示你选择以那种方式让github issue的评论和你的文章关联。
    theme = "github-light" # 样式主题，有github-light和github-dark两种
